config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  mount Ckeditor::Engine => '/ckeditor'
  resources :cheatsheets
  get 'tags/:tag', to: 'cheatsheets#index', as: :tag

  root 'cheatsheets#index'
  get 'cheatsheets/new'
  get 'cheatsheets/create'
  get 'cheatsheets/edit'
  get 'cheatsheets/update'
  get 'cheatsheets/destroy'
  get 'cheatsheets/show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cheatsheet.rb
class Cheatsheet < ApplicationRecord
  validates :title, :body, presence: true
  acts_as_taggable
  CATEGORY_LIST = ["HTML", "CSS", "Ruby on Rails", "Javascript"]
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
  Rails.application.config.assets.precompile += %w(ckeditor/config.js)
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cheatsheets_controller.rb
class CheatsheetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @cheatsheets = Cheatsheet.order("created_at desc")
    @cheatsheet_last = Cheatsheet.last
    if params[:title]
      @cheatsheets = Cheatsheet.where('title LIKE ?', "%#{params[:title]}%")
    elsif params[:tag]
      @cheatsheets = Cheatsheet.tagged_with(params[:tag])
    else
      @cheatsheets = Cheatsheet.all
    end
  end

  def show
    @cheatsheet = Cheatsheet.find(params[:id])
  end

  def new
    @cheatsheet = Cheatsheet.new
  end

  def create
    @cheatsheet = Cheatsheet.new(cheatsheet_params)
    @cheatsheet.save

    if @cheatsheet.save
      redirect_to @cheatsheet
    else
      render 'new'
    end
  end

  def edit
    @cheatsheet = Cheatsheet.find(params[:id])
  end

  def update
    @cheatsheet = Cheatsheet.find(params[:id])

    if @cheatsheet.update(cheatsheet_params)
      redirect_to @cheatsheet
    else
      render 'edit'
    end
  end

  def destroy
    @cheatsheet = Cheatsheet.find(params[:id])
    @cheatsheet.destroy

    redirect_to cheatsheets_path
  end

  private
  def cheatsheet_params
    params.require(:cheatsheet).permit(:category, :title, :body, :tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheatsheets_helper.rb
module CheatsheetsHelper
end

app/views/cheatsheets/_cheatsheet_form.html.erb
<%= form_for @cheatsheet do |f| %>
  <%= f.label :category, 'Language', :class => 'label' %>
  <div class="select">
  <%= f.select(:category, Cheatsheet::CATEGORY_LIST) %> <br>
  </div>

  <%= f.label :tag_list, 'Tags separated by commas', :class => 'label' %>
  <%= f.text_field :tag_list, value: @cheatsheet.tag_list.join(","), :class => 'input' %> <br>

  <%= f.label :title, 'Title', :class => 'label' %>
  <%= f.text_field :title, :class => 'input' %> <br>

  <%= f.label :body, 'Content', :class => 'label' %>
  <%= f.cktext_area :body %> <br>

  <% if current_page?(action: 'new') %>
    <%= f.submit 'Spread', :class => 'button is-primary is-outlined' %>
  <% end %>
  <% if current_page?(action: 'edit') %>
    <%= f.submit 'Update', :class => 'button is-primary is-outlined' %>
  <% end %>

<% end %>

app/views/cheatsheets/create.html.erb
<h1>Cheatsheets#create</h1>
<p>Find me in app/views/cheatsheets/create.html.erb</p>

app/views/cheatsheets/destroy.html.erb
<h1>Cheatsheets#destroy</h1>
<p>Find me in app/views/cheatsheets/destroy.html.erb</p>

app/views/cheatsheets/edit.html.erb
<div class="show-container">
  <h3>Editing “<%= @cheatsheet.title %>”</h3>

    <%= render 'cheatsheet_form' %>

</div>

app/views/cheatsheets/index.html.erb
<div class="columns">
  <div class="side-nav column is-3">
    <h3 class="side-menu-title">All cheatsheets</h3>
    <ul>
      <% @cheatsheets.each do |cheatsheet| %>
        <li><%= link_to cheatsheet.title, cheatsheet_path(cheatsheet) %> (in <em><%= cheatsheet.category %></em>)</li>
      <% end %>
    </ul>
  </div>

  <div class="index-main-container column is-9 is-offset-3">
    <div class="index-hero">
      <h1>Welcome to the web development cheatsheet</h1>
      <p>As I am learning web development on my own, I've created this app to upload my notes and the tips I find usefull in all kind of web developpment aspects.</p>
      <p>The content is going to evolve as I learn more and more stuff everyday.</p>
      <p>I'm happy to share all my findings with anyone. If you want to contact me, follow the link bellow ✌🏼</p>
      <%= mail_to 'mosser.romain@gmail.com', 'Email me', :class => 'button is-primary is-outlined' %>
      <hr>
    </div>

    <div class="index-last-post">
      <h2>Lastest post ⬇️</h2>
      <div class="category-container">
        <div class="language-icon">
          <% @cheatsheets.each do |c| %>
            <% if c.category == 'HTML' %>
              <%= image_tag('HTML5.svg') %>
            <% end %>
            <% if c.category == 'Ruby on Rails' %>
              <%= image_tag('rails.svg') %>
            <% end %>
            <% if c.category == 'CSS' %>
              <%= image_tag('CSS.svg') %>
            <% end %>
            <% if c.category == 'Javascript' %>
              <%= image_tag('javascript.svg') %>
            <% end %>
          <% end %>
        </div>
        <p>Published in <strong><%= @cheatsheet_last.category %></strong></p>
      </div>
      <h1><%= @cheatsheet_last.title %></h1>
      <%= @cheatsheet_last.body.html_safe %>
    </div>
  </div>

</div>

app/views/cheatsheets/new.html.erb
<div class="show-container">
    <h1>New cheatsheet</h1>
    <%= render 'cheatsheet_form' %>
</div>

app/views/cheatsheets/show.html.erb
<div class="show-container">
  <div class="category-container">
    <div class="language-icon">
      <% if @cheatsheet.category == 'HTML' %>
        <%= image_tag('HTML5.svg') %>
      <% end %>
      <% if @cheatsheet.category == 'Ruby on Rails' %>
        <%= image_tag('rails.svg') %>
      <% end %>
      <% if @cheatsheet.category == 'CSS' %>
        <%= image_tag('CSS.svg') %>
      <% end %>
      <% if @cheatsheet.category == 'Javascript' %>
        <%= image_tag('javascript.svg') %>
      <% end %>
    </div>
    <p>Published in <strong><%= @cheatsheet.category %></strong></p>
  </div>
  <p>Tags: <span class="tag-view"><%= raw @cheatsheet.tag_list.map { |t| link_to t, tag_path(t) }. join(', ') %></span></p>
  <h1><%= @cheatsheet.title %></h1>
  <%= @cheatsheet.body.html_safe %>

  <% if user_signed_in? %>
    <div class="crud-links">
      <%= link_to 'Edit', edit_cheatsheet_path, :class => 'button is-primary is-small is-outlined' %>
      <%= link_to 'Delete', @cheatsheet, method: :delete, data: {confirm: 'Wanna delete for sure? 🤔'}, :class => 'button is-danger is-small is-outlined' %>
    </div>
  <% end %>
</div>

app/views/cheatsheets/update.html.erb
<h1>Cheatsheets#update</h1>
<p>Find me in app/views/cheatsheets/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name=viewport content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag Ckeditor.cdn_url %>
  </head>

  <body>
    <div class="devise-messages">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <div class="top-nav">
      <nav>
        <ul>
          <li><%= link_to 'Home', root_path %></li>
          <li>
            <% if user_signed_in? %>
              <%= link_to 'New', new_cheatsheet_path, :class => 'button-new' %>
            <% end %>
          </li>
        </ul>
      </nav>
      <%= form_tag(cheatsheets_path, method: :get) do %>
        <div class="search-bar">
          <%= text_field_tag :title, params[:title], class: 'input is-small'  %>
          <%= submit_tag 'Search', name: nil, class: 'button is-small is-primary' %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>